name: loli
description: A sustainability-focused application.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0   # Sadece bir kez tanımlayın
  url_launcher: ^6.0.9
  geolocator: ^13.0.1
  pedometer: ^4.0.2
  fl_chart: ^0.69.0
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.6
  image_picker: ^1.1.2
  collection: ^1.18.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  string_scanner: ^1.2.0
  test_api: 0.7.2
  vm_service: 14.2.5

flutter:
  uses-material-design: true
